### ISSUE TITLE
Slow reacts falsely labeled bad

### ISSUE THREAD

**Issue by kkkesilchen** [Waifu/OsancTools#7] opened 2022-11-12 23:07 UTC
### Issue
Good slow reacts get classified as bad reacts: turning on the "Remove Bad Reacts" option removes the slow reacts, despite them getting colored green.
Example id for below: 16759.
### Screenshots and/or videos
![image](https://user-images.githubusercontent.com/92551892/201497991-7c4686cf-2187-47ac-a388-d6fb846a4559.png)
### Version
OsancTools v1.0.0.3

**Comment by Waifu** [comment] 2022-11-12 23:26
The issue is in `com.github.waifu.entities.React.parseItem()`. The last else statement in the slow case is within the for loop so a whisper (etc.) is set if the item is not in the Twilight Archmage item set, but it is in the ability set. A potential fix is to remove this else statement and keep track if the ability was found in any JSONArrays, if not then mark as a problem (outside the for loop).

**Comment by Waifu** [comment] 2022-11-15 03:45
Fixed with https://github.com/Waifu/OsancTools/commit/f4c93aa4c4d83a989bd4fc3bc91b923c5c4a83f7

**Closed by Waifu** 2022-11-15 03:45 UTC
